name: Workflow dispatch
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

jobs:
  printDeploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploy!!!!"
          echo "${GITHUB_REF#refs/heads/}"
          echo "github.head_ref"
          echo "${GITHUB_BASE_REF}"
          echo "${GITHUB_REF#refs/base/}"
