name: Workflow dispatch
on:
  workflow_dispatch:
    inputs:
      guide:
        description: 'デプロイできるよ'

jobs:
  printDeploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Deploy!!!!"
